Drop TABLE IF EXISTS classe;
CREATE TABLE classe (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(20) UNIQUE NOT NULL,
    nom VARCHAR(100) NOT NULL,
    capaciteMax INT NOT NULL,
    anneeScolaire VARCHAR(20) NOT NULL,
    typeDiplome ENUM('LICENCE', 'MASTERE', 'INGENIEUR', 'DOCTORAT') NOT NULL,
    niveauAnnee ENUM('PREMIERE_ANNEE', 'DEUXIEME_ANNEE', 'TROISIEME_ANNEE', 'QUATRIEME_ANNEE', 'CINQUIEME_ANNEE') NOT NULL,
    specialiteId BIGINT NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deletedAt DATETIME NULL,
    FOREIGN KEY (specialiteId) REFERENCES specialite(id)
);